name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          .\cmd\build.ps1
          $git_sha=(git rev-parse --short HEAD)

      - name: Go Publishr
        uses: PackagrIO/action-publishr-go@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        with:
          upload_assets: lmaa_$git_sha.exe
